<?php
//
// +------------------------------------------------------------------------+
// | PHP Version 5                                                          |
// +------------------------------------------------------------------------+
// | Copyright (c) All rights reserved.                                     |
// +------------------------------------------------------------------------+
// | File:                                                                  |
// +------------------------------------------------------------------------+
// | Author:                                                                |
// +------------------------------------------------------------------------+
//
// $Id$
//

namespace App\IekModel\Version1_0;
use bar\baz\source_with_namespace;


/**
* @author       Rich
*/
class Privilege extends IekModel
{
    const PRIVILEGES = [
        '1' => ['name' => 'publication',
            'description' => 'User edit publication',
            'table_name' => 'tblPublications',
            'is_active' =>true,
            'is_removed' => false,
        ],
        '2' => ['name' => 'comment',
            'description' => 'User edit comment',
            'table_name' => 'tblComments',
            'is_active' =>true,
            'is_removed' => false,
        ],
        '3' => ['name' => 'recommend',
            'description' => 'User recommend',
            'table_name' => '',
            'is_active' =>true,
            'is_removed' => false,
        ],
        '4' => ['name' => 'personInformation',
            'description' => 'User edit information',
            'table_name' => 'tblPeople',
            'is_active' =>true,
            'is_removed' => false,
        ],
        '5' => ['name' => 'folder',
            'description' => 'User edit folder',
            'table_name' => 'tblFolders',
            'is_active' =>true,
            'is_removed' => false,
        ],
        '6' => ['name' => 'group',
            'description' => 'User edit group',
            'table_name' => 'tblGroups',
            'is_active' =>true,
            'is_removed' => false,
        ],
        '7' => ['name' => 'messageCrowd',
            'description' => 'User edit message to crowd',
            'table_name' => 'tblMessageCrowds',
            'is_active' =>true,
            'is_removed' => false,
        ],
        '8' => ['name' => 'messageSingle',
            'description' => 'User edit message to single',
            'table_name' => 'tblMessageSingles',
            'is_active' =>true,
            'is_removed' => false,
        ],
        '9' => ['name' => 'complaint',
            'description' => 'User edit complaint',
            'table_name' => 'tblComplaints',
            'is_active' =>true,
            'is_removed' => false,
        ],
        '10' => ['name' => 'appeal',
            'description' => 'User edit appeal',
            'table_name' => 'tblAppeals',
            'is_active' =>true,
            'is_removed' => false,
        ],
        '11' => ['name' => 'advice',
            'description' => 'User edit advice',
            'table_name' => 'tblAdvice',
            'is_active' =>true,
            'is_removed' => false,
        ],
        '12' => ['name' => 'adviceReply',
            'description' => 'Manager reply advice',
            'table_name' => 'tblAdviceReplies',
            'is_active' =>true,
            'is_removed' => false,
        ],
        '13' => ['name' => 'activity',
            'description' => 'Manager edit activity',
            'table_name' => 'tblActivities',
            'is_active' =>true,
            'is_removed' => false,
        ],
        '14' => ['name' => 'vote',
            'description' => 'Manager edit vote',
            'table_name' => 'tblVotes',
            'is_active' =>true,
            'is_removed' => false,
        ],
        '15' => ['name' => 'joinActivity',
            'description' => 'User join activity',
            'table_name' => 'tblActivityJoins',
            'is_active' =>true,
            'is_removed' => false,
        ],
        '16' => ['name' => 'joinVote',
            'description' => 'User join vote',
            'table_name' => 'tblVoteJoins',
            'is_active' =>true,
            'is_removed' => false,
        ],
        '17' => ['name' => 'activityComment',
            'description' => 'User comment activity',
            'table_name' => 'tblActivityComments',
            'is_active' =>true,
            'is_removed' => false,
        ],
        '18' => ['name' => 'viewPublication',
            'description' => 'User view publication',
            'table_name' => 'tblPublicationViewers',
            'is_active' =>true,
            'is_removed' => false,
        ],
        '19' => ['name' => 'viewPerson',
            'description' => 'User view others',
            'table_name' => 'tblPersonViewers',
            'is_active' =>true,
            'is_removed' => false,
        ],
        '20' => ['name' => 'viewFolder',
            'description' => 'User view folder',
            'table_name' => 'tblFolderViewers',
            'is_active' =>true,
            'is_removed' => false,
        ],
        '21' => ['name' => 'viewActivity',
            'description' => 'User view activity',
            'table_name' => 'tblActivityViewers',
            'is_active' =>true,
            'is_removed' => false,
        ],
        '22' => ['name' => 'viewVote',
            'description' => 'User view vote',
            'table_name' => 'tblVoteViewers',
            'is_active' =>true,
            'is_removed' => false,
        ],
        '23' => ['name' => 'likePublication',
            'description' => 'User like publication',
            'table_name' => 'tblPublicationLikes',
            'is_active' =>true,
            'is_removed' => false,
        ],
        '24' => ['name' => 'likeComment',
            'description' => 'User like comment',
            'table_name' => 'tblCommentLikes',
            'is_active' =>true,
            'is_removed' => false,
        ],
        '25' => ['name' => 'likePerson',
            'description' => 'User like others',
            'table_name' => 'tblPersonLikes',
            'is_active' =>true,
            'is_removed' => false,
        ],
        '26' => ['name' => 'recommendPublication',
            'description' => 'User recommend publication',
            'table_name' => 'tblPublicationRecommends',
            'is_active' =>true,
            'is_removed' => false,
        ],
        '27' => ['name' => 'recommendComment',
            'description' => 'User recommends comment',
            'table_name' => 'tblCommentRecommends',
            'is_active' =>true,
            'is_removed' => false,
        ],
        '28' => ['name' => 'recommendPerson',
            'description' => 'User recommends others',
            'table_name' => 'tblPersonRecommends',
            'is_active' =>true,
            'is_removed' => false,
        ],
        '29' => ['name' => 'followPerson',
            'description' => 'User focuses others',
            'table_name' => 'tblPersonFollows',
            'is_active' =>true,
            'is_removed' => false,
        ],
        '30' => ['name' => 'blockPerson',
            'description' => 'User block others',
            'table_name' => 'tblPersonBlocks',
            'is_active' =>true,
            'is_removed' => false,
        ],
        '31' => ['name' => 'collectPublication',
            'description' => 'User focuses publication',
            'table_name' => 'tblFolderCollections',
            'is_active' =>true,
            'is_removed' => false,
        ],
        '32' => ['name' => 'followFolder',
            'description' => 'User focuses folder',
            'table_name' => 'tblFolderFollows',
            'is_active' =>true,
            'is_removed' => false,
        ],
        '33' => ['name' => 'iwall',
            'description' => 'User edit iwall',
            'table_name' => 'tblIwalls',
            'is_active' =>true,
            'is_removed' => false,
        ],
        '34' => ['name' => 'likeIwall',
            'description' => 'User like iwall',
            'table_name' => 'tblIwallLikes',
            'is_active' =>true,
            'is_removed' => false,
        ],
        '35' => ['name' => 'recommendIwall',
            'description' => 'User recommends iwall',
            'table_name' => 'tblIwallRecommends',
            'is_active' =>true,
            'is_removed' => false,
        ],
        '36' => ['name' => 'commentIwall',
            'description' => 'User comments iwall',
            'table_name' => 'tblIwallComments',
            'is_active' =>true,
            'is_removed' => false,
        ],
        '37' => ['name' => 'collectIwall',
            'description' => 'User focuses iwall',
            'table_name' => 'tblIwallCollections',
            'is_active' =>true,
            'is_removed' => false,
        ],
        '38' => ['name' => 'notice',
            'description' => 'Manager edit notice',
            'table_name' => 'tblNotices',
            'is_active' =>true,
            'is_removed' => false,
        ],
        '39' => ['name' => 'help',
            'description' => 'Manager edit help',
            'table_name' => 'tblHelps',
            'is_active' =>true,
            'is_removed' => false,
        ],
        '40' => ['name' => 'policy',
            'description' => 'Manager edit policy',
            'table_name' => 'tblPolicies',
            'is_active' =>true,
            'is_removed' => false,
        ],
        '41' => ['name' => 'viewNotice',
            'description' => 'User view notice',
            'table_name' => 'tblNoticeViewers',
            'is_active' =>true,
            'is_removed' => false,
        ],
        '42' => ['name' => 'viewPolicy',
            'description' => 'User view policy',
            'table_name' => 'tblPolicyViewers',
            'is_active' =>true,
            'is_removed' => false,
        ],
        '43' => ['name' => 'viewHelp',
            'description' => 'User view help',
            'table_name' => 'tblHelpViewers',
            'is_active' =>true,
            'is_removed' => false,
        ],
        '44' => ['name' => 'questionHelp',
            'description' => 'User asks question to help',
            'table_name' => 'tblHelpQuestions',
            'is_active' =>true,
            'is_removed' => false,
        ],
        '45' => ['name' => 'replyQuestion',
            'description' => 'Manager reply user\'s question',
            'table_name' => 'tblQuestionReplies',
            'is_active' =>true,
            'is_removed' => false,
        ],
        '46' => ['name' => 'publicationOfficialRecommend',
            'description' => 'User officially recommend publication',
            'table_name' => 'tblQuestionReplies',
            'is_active' =>true,
            'is_removed' => false,
        ],
        '47' => ['name' => 'publicationCommentInvite',
            'description' => 'User invite others to comment publication',
            'is_active' =>true,
            'is_removed' => false,
        ],
        '48' => ['name' => 'publicationEditInvite',
            'description' => 'User invite others to edit publication',
            'table_name' => 'tblPublicationInvites',
            'is_active' =>true,
            'is_removed' => false,
        ],
        '49' => ['name' => 'iwallEditInvite',
            'description' => 'User invite others to edit iwall',
            'table_name' => 'tblIwallInvites',
            'is_active' =>true,
            'is_removed' => false,
        ],
        '50' => ['name' => 'joinGroupInvite',
            'description' => 'User invite others to join group',
            'table_name' => 'tblGroupInvites',
            'is_active' =>true,
            'is_removed' => false,
        ],
        '51' => ['name' => 'joinGroupRequest',
            'description' => 'User requests to join group',
            'table_name' => 'tblGroupRequests',
            'is_active' =>true,
            'is_removed' => false,
        ],
        '52' => ['name' => 'groupMember',
            'description' => 'User modify group member',
            'table_name' => 'tblGroupMembers',
            'is_active' =>true,
            'is_removed' => false,
        ],
        '53' => ['name' => 'groupSubject',
            'description' => 'User publish group subject',
            'table_name' => 'tblSubjects',
            'is_active' =>true,
            'is_removed' => false,
        ],
        '54' => ['name' => 'systemSettings',
            'description' => 'Manager set system function',
            'table_name' => 'tblSystemSettings',
            'is_active' =>true,
            'is_removed' => false,
        ],
        '55' => ['name' => 'reword',
            'description' => 'Manager rewords user',
            'table_name' => 'tblRewords',
            'is_active' =>true,
            'is_removed' => false,
        ],
        '56' => ['name' => 'share',
            'description' => 'User share link',
            'table_name' => 'tblShares',
            'is_active' =>true,
            'is_removed' => false,
        ],
        '57' => ['name' => 'login',
            'description' => 'User login',
            'table_name' => 'tblLogins',
            'is_active' =>true,
            'is_removed' => false,
        ],
        '58' => ['name' => 'draft',
            'description' => 'The draft store for user',
            'table_name' => 'tblPublications',
            'is_active' =>true,
            'is_removed' => false,
        ],
    ];

    /**
    * @var  id                  INT8
    * @var  name                String
    * @var  description         String
    * @var  table_name          String
    * @var  created_at          timestamps
    * @var  updated_at          timestamps
    * @var  is_active           Boolean
    * @var  is_removed          Boolean
    */

    // public $timestamps = false;
    // public $incrementing = false;
    public $primaryKey = 'id';
    protected $table = 'tblPrivileges';

}

?>
